# Generated by Django 4.2.28 on 2026-03-10 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='campus',
            field=models.CharField(choices=[('xihai', '西海岸校区'), ('laoshan', '崂山校区'), ('yushan', '鱼山校区')], db_index=True, default='xihai', max_length=20, verbose_name='校区'),
        ),
    ]
