# Generated by Django 4.2.28 on 2026-03-10 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='campus',
            field=models.CharField(choices=[('xihai', '西海岸校区'), ('laoshan', '崂山校区'), ('yushan', '鱼山校区')], db_index=True, default='xihai', max_length=20, verbose_name='校区'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['campus', 'status', '-created_at'], name='products_campus_c7afa2_idx'),
        ),
    ]
